"""
Seed the scenes database with sample locations.
Run once to populate initial data:
    python seed_scenes.py

You can also add scenes interactively via the Gradio UI (Manage Scenes tab).
"""
import os
import sys
from scene_db import add_scene, list_scenes, SCENES_DIR

# Sample scenes - add your own images to assets/scenes/ and update paths here
SAMPLE_SCENES = [
    {
        "name": "平江路",
        "category": "street",
        "description": "",  # Will be auto-generated by M3 vision on first use
        "image_file": "pingjianlu.jpg",  # Place this file in assets/scenes/
    },
    {
        "name": "山塘街",
        "category": "street",
        "description": "",
        "image_file": "shantangjie.jpg",
    },
    {
        "name": "西湖断桥",
        "category": "landmark",
        "description": "",
        "image_file": "xihu_duanqiao.jpg",
    },
    {
        "name": "外滩",
        "category": "landmark",
        "description": "",
        "image_file": "waitan.jpg",
    },
    {
        "name": "南京路步行街",
        "category": "street",
        "description": "",
        "image_file": "nanjinglu.jpg",
    },
]


def seed():
    existing = {s["name"] for s in list_scenes()}
    added = 0

    for scene in SAMPLE_SCENES:
        if scene["name"] in existing:
            print(f"  ⏭️  '{scene['name']}' already exists, skipping.")
            continue

        image_path = os.path.join(SCENES_DIR, scene["image_file"])
        if not os.path.exists(image_path):
            print(f"  ⚠️  Image not found: {image_path} — skipping '{scene['name']}'")
            print(f"       → Place your image at: {os.path.abspath(image_path)}")
            continue

        scene_id = add_scene(
            name=scene["name"],
            image_path=image_path,
            description=scene["description"],
            category=scene["category"],
        )
        print(f"  ✅ Added '{scene['name']}' (id={scene_id})")
        added += 1

    print(f"\nDone! Added {added} scene(s). Total scenes: {len(list_scenes())}")
    print(f"\nTo add scene images, place them in: {os.path.abspath(SCENES_DIR)}/")
    print("Or use the Gradio UI → Manage Scenes tab to upload directly.")


if __name__ == "__main__":
    print("🌆 Seeding scenes database...\n")
    seed()
